version: 2.0
jobs:
 dockerize:
   machine: true
   steps:
     - checkout
     # Login to docker
     - run: docker login -u rezabd9 -p Reza7163895

     # build the application image
     - run: docker build -t circleci/openjdk .

     # deploy the image
     - run: docker push circleci/openjdk

          name: test
          command: |
            gradle test
      - store_test_results:
                           path: test-results
      - store_artifacts:
                       path: /code/test-results
                       destination: prefix

                       version: 2
