version: 2.0
jobs:
test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          name: test123
          command: gradle test
          -store test results:
                             path: build/test-results
      
package:
    docker:
      - image: circleci/openjdk:8-jdk
        steps:
           - checkout
           - run: 
                name: test123
                command: gradle jar
                path: build/libs
                destination: prfix
     
workflows: 
  version: 2
  do_workflow:
        jobs :
             - test
             - package:
               require:
                       -test
      